/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.entities.Jobs;
import app.entities.Users;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.criteria.CriteriaQuery;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JB
 */
public class JobsSelector extends javax.swing.JPanel {
    private EntityManagerFactory factory;
    private List<Jobs> notSelectedJobs, selectedJobs;
    private DefaultListModel listModel;
    
    
    /**
     * Creates new form JobsSelector
     */
    public JobsSelector() {
        initComponents();
    }
    
    
    /**
     * Need this because constructor can't have any arguments.
     * @param factory
     * @param user null if should be blank, otherwise supply user to fill his data
     */
    public void initialize(EntityManagerFactory factory, Users user) {
        this.factory = factory;
        reset();
        if (user != null) {
            for (Jobs job : user.getJobsCollection()) {
                moveToSelected(notSelectedJobs.indexOf(job));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setPreferredSize(new java.awt.Dimension(258, 98));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setVisibleRowCount(6);
        jScrollPane2.setViewportView(jList1);

        jButton1.setText("Add job");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Remove highlighted");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 200));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setText("New job name:");

        jLabel2.setText("Description:");

        jButton3.setText("Create new job");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jTextField2)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        moveToSelected(jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int index = jList1.getSelectedIndex();
        if (index == -1) { return;}
        Jobs j = selectedJobs.get(index);
        selectedJobs.remove(index);
        listModel.removeElementAt(index);
        if (j.getJobId() == null) {
            //Job not in database yet
            return;
        }
        notSelectedJobs.add(j);
        jComboBox1.addItem(j.getName());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String name = jTextField1.getText();
        String description = jTextField2.getText();
        if (jTextField1.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, 
                    "Job name cannot be empty!",
                    "Job could not be created",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jobExists(name)) {
            JOptionPane.showMessageDialog(null, 
                    "Job already exists. Try to find it in the combo box or the list.",
                    "Job could not be created",
                    JOptionPane.ERROR_MESSAGE);
            return; 
        }
        Jobs job = new Jobs();
        job.setName(name);
        job.setDescription(description);
        job.setUsersCollection(new ArrayList<Users>());
        selectedJobs.add(job);
        listModel.addElement("<html><b>" + job.getName() + "</b><br> " + job.getDescription() + "</html>");
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
    
    private List<Jobs> getJobsList() {
        EntityManager em = factory.createEntityManager();
        CriteriaQuery<Jobs> cq = em.getCriteriaBuilder().createQuery(Jobs.class);
        cq.select(cq.from(Jobs.class));
        return em.createQuery(cq).getResultList();
    }
    
    private boolean jobExists(String name) {
        for (Jobs j : notSelectedJobs) {
            if (j.getName().equals(name)) {
                return true;
            }
        }
        for (Jobs j : selectedJobs) {
            if (j.getName().equals(name)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * @return The list of selected jobs. This is the main result of this component 
     */
    public List<Jobs> getSelectedJobs() {
        return selectedJobs;
    }
    
    /**
     * Resets to the original state.
     */
    public void reset() {
        notSelectedJobs = getJobsList();
        selectedJobs = new ArrayList<>();
        jComboBox1.removeAllItems();
        for (Jobs j : notSelectedJobs) {
            jComboBox1.addItem(j.getName());
        }
        jList1.setModel(listModel = new DefaultListModel());  
    }
    
    private void moveToSelected(int id) {
        String item = (String) jComboBox1.getItemAt(id);
        if (item == null) { return;}
        Jobs j = notSelectedJobs.get(id);
        notSelectedJobs.remove(id);
        selectedJobs.add(j);
        listModel.addElement("<html><b>" + j.getName() + "</b><br> " + j.getDescription() + "</html>");
        jComboBox1.removeItem(item);
    }
    
}
